# Generated by Django 3.2.16 on 2025-08-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('salary', models.IntegerField()),
                ('company', models.CharField(max_length=128)),
                ('allowed_time', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(max_length=64)),
                ('site_id', models.CharField(max_length=128)),
                ('company_rating', models.FloatField()),
            ],
        ),
    ]
