# Generated by Django 3.2.16 on 2025-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
