# Generated by Django 3.2.16 on 2025-08-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancies_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='salary',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='salary_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
