# Generated by Django 3.2.16 on 2025-08-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20250817_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='salary_data',
        ),
    ]
