# Generated by Django 3.2.16 on 2025-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_remove_vacancies_salary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='salary_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='salary_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
