# Generated by Django 3.2.16 on 2025-08-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_auto_20250817_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='allowed_time',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='company_rating',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='salary_to',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='site',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='site_id',
        ),
    ]
