# Generated by Django 3.2.16 on 2025-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_auto_20250817_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='site_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
